### ISSUE TITLE
로그아웃 기능 필요

### ISSUE THREAD

**Issue by Indian966** [lns960712/SecretaryKim#1]
로그아웃 후 다시 로그인할때 제대로 인증 절차를 거치는지 확인 필요

**Comment by lns960712** [comment]
레이아웃에 로그아웃버튼추가 및 메소드연결, 동작확인 부탁합니다!!

**Comment by Indian966** [comment]
메소드 정상적으로 작동하고
로그아웃 테스트 결과 이상 없음
