### ISSUE TITLE
BranchActivity버그수정필요

### ISSUE THREAD

**Issue by lns960712** [lns960712/SecretaryKim#3]
BranchActivity에 회의종료 기능과 참여자표시기능이 충돌하는 버그발견.

**Comment by Indian966** [comment]
레퍼런스 구조가 잘못되었습니다.
onchild 메소드를 이용해서 리스너가 쓸 수 있는 레퍼런스를 상세하게 나누었으니 확인후에 
이슈 닫아주시기 바랍니다.

**Comment by lns960712** [comment]
확인!!!
